spring:
  datasource:
    url: jdbc:mysql://captour-2024.cnwgauwkgavp.ap-northeast-2.rds.amazonaws.com:3306/captour_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: km923009!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      show_sql: true
      format_sql: true
      use_sql_comments: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000